// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBooks.Service.Database;

#nullable disable

namespace MyBooks.Service.Migrations
{
    [DbContext(typeof(MyBooksContext))]
    [Migration("20260628182903_AddSlikaToKnjiga")]
    partial class AddSlikaToKnjiga
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyBooks.Service.Database.Citat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BrojStranice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdKnjiga")
                        .HasColumnType("int");

                    b.Property<bool?>("JeOmiljeni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TekstCitata")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKnjiga");

                    b.ToTable("Citat");
                });

            modelBuilder.Entity("MyBooks.Service.Database.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DatumKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DatumPocetka")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DatumZavrsetka")
                        .HasColumnType("date");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Ocjena")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recenzija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Knjiga");
                });

            modelBuilder.Entity("MyBooks.Service.Database.KnjigaZanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdKnjiga")
                        .HasColumnType("int");

                    b.Property<int>("IdZanr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKnjiga");

                    b.HasIndex("IdZanr");

                    b.ToTable("KnjigaZanr");
                });

            modelBuilder.Entity("MyBooks.Service.Database.WishKnjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Autor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DatumKreiranja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prioritet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WishKnjiga");
                });

            modelBuilder.Entity("MyBooks.Service.Database.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Zanr");
                });

            modelBuilder.Entity("MyBooks.Service.Database.Citat", b =>
                {
                    b.HasOne("MyBooks.Service.Database.Knjiga", "IdKnjigaNavigation")
                        .WithMany("Citats")
                        .HasForeignKey("IdKnjiga")
                        .IsRequired()
                        .HasConstraintName("FK__Citat__IdKnjiga__29572725");

                    b.Navigation("IdKnjigaNavigation");
                });

            modelBuilder.Entity("MyBooks.Service.Database.KnjigaZanr", b =>
                {
                    b.HasOne("MyBooks.Service.Database.Knjiga", "IdKnjigaNavigation")
                        .WithMany("KnjigaZanrs")
                        .HasForeignKey("IdKnjiga")
                        .IsRequired()
                        .HasConstraintName("FK__KnjigaZan__IdKnj__2E1BDC42");

                    b.HasOne("MyBooks.Service.Database.Zanr", "IdZanrNavigation")
                        .WithMany("KnjigaZanrs")
                        .HasForeignKey("IdZanr")
                        .IsRequired()
                        .HasConstraintName("FK__KnjigaZan__IdZan__2F10007B");

                    b.Navigation("IdKnjigaNavigation");

                    b.Navigation("IdZanrNavigation");
                });

            modelBuilder.Entity("MyBooks.Service.Database.Knjiga", b =>
                {
                    b.Navigation("Citats");

                    b.Navigation("KnjigaZanrs");
                });

            modelBuilder.Entity("MyBooks.Service.Database.Zanr", b =>
                {
                    b.Navigation("KnjigaZanrs");
                });
#pragma warning restore 612, 618
        }
    }
}
